name: Lint

on:
    workflow_call:
        inputs:
            app_directory:
                description: 'Directory of the application within the repository'
                required: false
                type: string
                default: '.'

jobs:
    lint:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ${{ inputs.app_directory }}

        steps:
            - name: Download prepared artifact
              uses: actions/download-artifact@v4
              with:
                name: prepared-source-artifact
                path: .

            - name: Install linting tools
              run: |
                  pip install ruff black

            - name: Run ruff linting
              run: |
                    ruff check .

            - name: Run black linting
              run: |
                    black --check .

            